### ISSUE TITLE
パートナー制度

### ISSUE THREAD

**Issue by inc2734** [inc2734/snow-monkey-official-website#16]
https://wpsnowmonkey.slack.com/archives/C01DYUA2UJH/p1604544293011200?thread_ts=1604537212.005700&cid=C01DYUA2UJH

> いちコミュニティ参加者として、Snow Monkeyパートナー（エヴァンジェリスト？名称はわかんないけど…）は、
> ・Snow Monkeyのフィロソフィーを理解している
> ・根幹のGPLを理解している
> ・オープンソース活動を理解している
> ・個々の利益よりもコミュニティの利益を優先できる（結果的に個々の利益になる活動は素敵だと思っています）
> など、取り組みを理解した上で、Snow Monkeyの認知PR向上や、コミュニティの醸成を加速してくれる人がなってくれるとみんなが喜ぶと思うので、そういった観点などの判断基準を明示した上で、パートナーの横の繋がりなども広がっていくと、それがSnow Monkeyエコシステムになっていくだろうなーと妄想しておるところです。

AWS ヒーローというのもあるっぽい。一応ブレインストーミング的に思いついたものを列挙。

- パートナー
- エバンジェリスト
- ヒーロー
- ロックスター
- ニンジャ
- スペシャリスト
- プロフェッショナル
- コントリビューター
- エキスパート
- ハピネス○○
- オルタナティブ○○

参考：
https://newspicks.com/news/3472663/

**Comment by Olein-jp** [comment]
名称って悩ましいですよね…

**Comment by Olein-jp** [comment]
パートナー
> 共同で仕事をする相手。相棒。

エバンジェリスト
> 製品などの啓発・宣伝を行う人。

という意味でこの場合使われるかと考えると、Snow Monkey エコシステムの「一員」として捉えるのであれば「パートナー」という言葉の方が適切なのかもしれませんね。

エバンジェリストだと、プロダクトを広める人という意味合いが強くなってしまって、若干仲間感が弱く捉えられる可能性がありそうですねー。

**Comment by inc2734** [comment]
なるほど。結果的に広がってほしいとは思うけど、積極的に広めてほしいというのはやりたいことと違うので、パートナーのほうが意味的にはあっている気がしますね。ありがとうございます！

**Comment by inc2734** [comment]
つくったのでクローズ。
https://snow-monkey.2inc.org/snow-monkey-expert/
